Create the html and css files
thasipablo/video_in_html pull request #1
Opened 2023-06-12 22:16 UTC by thasipablo

What I did:

- create index.html
- create style.css 
- create LICENSE file
- remove license file extension in README reference link

2023-06-12 22:46 UTC, thasipablo reviewed
Hey, You did a great job 👍. 
Make sure there are no linter errors and consider all the suggestions in this review. 
Good coding.

2023-06-12 22:46 UTC, thasipablo commented on index.html
> +        <div class="profile">profile</div>
Good work. You've used semantic tags very well throughout the page. But this tag should be replaced by a button because it's supposed to be clicked.

2023-06-12 22:46 UTC, thasipablo commented on index.html
> +        </main>
The main tag should be used only to wrap up the main content of the whole page.

2023-06-12 22:46 UTC, thasipablo commented on style.css
> +}
Good job. Your CSS file is clean 👍 
Try to use a grid display on the main container and display flex on the embedded items.

2023-06-12 22:57 UTC, shahadat3669 requested changes
Hi @thasipablo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
✅ You give inline-comment.
✅ Mention at least two changes
✅ Provide suggestions to the student

## Required Changes ♻️
Your review meets half of the project requirements that require you to 

- [x] Make a review using the GitHub inline comments feature ✔️ 
- [x] Mention at least two changes that you feel need changes ✔️.
- [x] However, mentioning changes with explaining why making that change is necessary is not yet met ❌

For example, I appreciate your attention to the matter regarding the main tag. Your observation is valid. But your comment needs some improvements. It is important to explain why such changes are necessary🧹. To comment the requirement that "The main tag should be used only to wrap up the main content of the whole page" along with the reasoning, you could phrase it as follows:

"It is crucial to adhere to the guideline of using the `<main>` tag solely to enclose the main content of the entire page. This practice ensures proper semantic structuring and improves accessibility, as assistive technologies rely on the `<main>` tag to identify and navigate to the primary content. By reserving the `<main>` tag for the main content exclusively, we maintain consistency, enhance usability, and promote web standards compliance. [Learn more](https://web.dev/learn/html/headings-and-sections/#outlining-the-lessbodygreater-of-mlwcom)" 👍 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## ⚠️ WARNING ⚠️
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 08:21 UTC, thasipablo commented on index.html
> +        </main>
The `<main>` tag helps screen readers and other assistive technologies understand where the main content begins. As per W3C standards it should only be used once per document. Using more than one, the w3c validation will fail.
Find more information [here](https://www.w3schools.com/tags/tag_main.asp).

2023-06-13 08:35 UTC, shahadat3669 requested changes
Hi @thasipablo , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights


 ## Required Changes ♻️

Great job! 👍 As per my previous request, I can see that you have updated your comment, and it looks good. However, I have a couple of suggestions to further enhance the feedback:

1. Instead of adding a new summary comment, could you please 🙏 consider either updating the existing inline comment or adding a new inline comment? This will help maintain a clear and organized feedback trail, making it easier for the author to follow the suggested changes.

2. Furthermore, please take a moment to review and edit [this comment](https://github.com/thasipablo/video_in_html/pull/1#discussion_r1227312291) 👇. It appears that this comment also requires some updates. I kindly request you to provide an explanation, including the "why" behind the requested change. Adding the "why" is an essential aspect of providing constructive feedback as it helps the author understand the reasoning behind possible improvements, fostering a collaborative approach. 👍

![image](https://github.com/thasipablo/video_in_html/assets/55840999/31885de7-9ba5-4caf-b231-1c179b220ee1)


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 09:50 UTC, thasipablo commented
Thank you @shahadat3669 for your feedbacks.

2023-06-13 09:56 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @thasipablo 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Comments are phrased politely ✔
- Each comment has a proper explanation as to "why" ✔
- Comments are clear and easy to understand ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-14 22:15 UTC, merged